version: 2
updates:
  # Maintain Python dependencies for api.
  - package-ecosystem: "pip"
    directory: "api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "api/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies for api test.
  - package-ecosystem: "pip"
    directory: "test/api/"
    schedule:
      interval: "weekly"

  # Maintain npm dependencies for sdk.
  - package-ecosystem: "npm"
    directory: "sdk/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies for sdk test.
  - package-ecosystem: "npm"
    directory: "test/sdk/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies for database.
  - package-ecosystem: "pip"
    directory: "database/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "database/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies for database test.
  - package-ecosystem: "npm"
    directory: "test/database/"
    schedule:
      interval: "weekly"

  # Maintain npm dependencies for web.
  - package-ecosystem: "npm"
    directory: "web/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies for web test.
  - package-ecosystem: "npm"
    directory: "test/web/"
    schedule:
      interval: "weekly"

  # Maintain npm dependencies for infrastructure.
  - package-ecosystem: "npm"
    directory: "infrastructure/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
