openapi: "3.0.0"

info:
  title: OpenAlchemy Package
  description: API backing the OpenAlchemy package service
  version: "0.1"

servers:
  - url: https://package.api.openalchemy.io/v1

paths:
  /specs/{spec_id}:
    put:
      summary: Create or update a new spec
      operationId: library.specs.put
      parameters:
        - in: path
          name: spec_id
          schema:
            $ref: "#/components/schemas/SpecId"
          required: true
          description: The id of the spec
      requestBody:
        description: The spec to store or update
        required: true
        content:
          text/plain:
            schema:
              $ref: "#/components/schemas/SpecValue"
      responses:
        204:
          description: The spec has been stored
        500:
          description: Something went wrong whilst saving the spec
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    SpecId:
      description: The id of an OpenAPI specification
      type: string
    SpecValue:
      description: The value of an OpenAPI specification
      type: string
