openapi: "3.0.0"

info:
  title: OpenAlchemy Package
  description: API backing the OpenAlchemy package service
  version: "0.1"

servers:
  - url: https://package.api.openalchemy.io/v1

security:
  - bearerAuth: []

paths:
  /specs:
    get:
      summary: List all available specs
      operationId: library.specs.list_
      responses:
        200:
          description: All the available specs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SpecId"
        401:
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
  /specs/{spec_id}:
    get:
      summary: Retrieve a spec
      operationId: library.specs.get
      parameters:
        - $ref: "#/components/parameters/SpecId"
      responses:
        200:
          description: The requested spec
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/SpecValue"
        401:
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Spec was not found
          content:
            text/plain:
              schema:
                type: string
    put:
      summary: Create or update a new spec
      operationId: library.specs.put
      parameters:
        - $ref: "#/components/parameters/SpecId"
        - in: header
          name: X-LANGUAGE
          description: The language of the spec
          required: true
          schema:
            type: string
            enum:
              - JSON
              - YAML
      requestBody:
        description: The spec to store or update
        required: true
        content:
          text/plain:
            schema:
              $ref: "#/components/schemas/SpecValue"
      responses:
        204:
          description: The spec has been stored
        500:
          description: Something went wrong whilst saving the spec
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
        402:
          description: Payment required
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: Delete a spec
      operationId: library.specs.delete
      parameters:
        - $ref: "#/components/parameters/SpecId"
      responses:
        204:
          description: The spec has been deleted
        401:
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
  /specs/{spec_id}/versions:
    get:
      summary: List all available versions for a spec
      operationId: library.specs.versions.list_
      parameters:
        - $ref: "#/components/parameters/SpecId"
      responses:
        200:
          description: All the available versions for a spec
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SpecVersion"
        401:
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Spec was not found
          content:
            text/plain:
              schema:
                type: string

components:
  parameters:
    SpecId:
      in: path
      name: spec_id
      schema:
        $ref: "#/components/schemas/SpecId"
      required: true
      description: The id of the spec
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      x-bearerInfoFunc: library.helpers.token.decode
  schemas:
    SpecId:
      description: The id of an OpenAPI specification
      type: string
    SpecValue:
      description: The value of an OpenAPI specification
      type: string
    SpecVersion:
      description: The version of an OpenAPI specification
      type: string
