name: Build CI-CD

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-cd-build.yaml"
      - "build/**"
      - "test/index/**"
      - "infrastructure/**"
      - "!infrastructure/lib/*-stack.ts"
      - "infrastructure/lib/build-stack.ts"
      - "!infrastructure/test/**"
      - "!**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pipenv
            build/.venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('build/Pipfile.lock') }}
      - name: install dependencies
        working-directory: ./build
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: run tests
        working-directory: ./build
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv run test || pipenv --rm && pipenv install --dev && pipenv run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: build/dist/deployment-package.zip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-slim-${{ hashFiles('build/**') }}
      - name: set up python
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: create package
        working-directory: ./build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          pipenv lock -r > requirements.txt
          ../remove-lambda-built-in-dependencies.sh
          pip install --no-deps -r lambda-requirements.txt --target dist
          cp -r app.py library dist/
          cd dist
          zip -r deployment-package.zip .
      - name: upload artifacts for release
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/dist/deployment-package.zip

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: cache node modules
        id: cache-node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: infrastructure/node_modules
          key: ${{ runner.os }}-infrastructure-${{ env.cache-name }}-${{ hashFiles('infrastructure/package-lock.json') }}
      - name: install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        working-directory: ./infrastructure
        run: npm install
      - name: retrieve build deployment package
        uses: actions/download-artifact@v2
        with:
          name: build
          path: infrastructure/resources/build/
      - name: deploy
        working-directory: ./infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          ALARM_EMAIL_ADDRESS: ${{ secrets.ALARM_EMAIL_ADDRESS }}
        run: |
          npm run deploy:build

  production-test:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: install dependencies
        working-directory: ./test/index/
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: Run tests
        working-directory: ./test/index/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          TEST_USERNAME: ${{ secrets.TEST_USERNAME_INDEX }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD_INDEX }}
        run: |
          pipenv run test
