name: Security Periodic Production Tests

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  database:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYPI_MIRROR:
          - https://test.pypi.org/simple/
          - https://pypi.org/simple/
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv poetry
      - name: install dependencies
        working-directory: test/security
        env:
          PYPI_MIRROR: ${{ matrix.PYPI_MIRROR }}
          VERSION: "1.0.4"
        run: |
          # Check that project version equal requested version
          cd ../../security
          PROJECT_VERSION=$(poetry version -s)
          cd -
          [[ "$VERSION" == "$PROJECT_VERSION" ]]
          pipenv install --dev
      - name: run tests
        working-directory: test/security
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          pipenv run test
