name: API Periodic Production Tests

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: test/api/.venv
          key: ${{ runner.os }}-test-api-${{ hashFiles('test/api/Pipfile.lock') }}
      - name: install dependencies
        working-directory: ./test/api/
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: Run tests
        working-directory: ./test/api/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME_API }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD_API }}
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install
          pipenv run test
