name: Database Periodic Production Tests

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/production-test-database.yaml"
      - "test/database/**"

jobs:
  database:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYPI_MIRROR:
          - https://test.pypi.org/simple/
          - https://pypi.org/simple/
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv poetry
      - name: get version
        working-directory: database
        run: |
          echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: install dependencies
        working-directory: test/database
        env:
          PYPI_MIRROR: ${{ matrix.PYPI_MIRROR }}
        run: |
          pipenv install --dev
      - name: run tests
        working-directory: test/database
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: PROD
        run: |
          pipenv run test
