name: Database Periodic Production Tests

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  database:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYPI_MIRROR:
          - https://test.pypi.org/simple/
          - https://pypi.org/simple/
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: install dependencies
        working-directory: test/database
        env:
          PYPI_MIRROR: ${{ matrix.PYPI_MIRROR }}
          VERSION: "1.2.2"
        run: |
          pipenv install --dev
      - name: run tests
        working-directory: test/database
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: PROD
        run: |
          pipenv run test
